{% set name = "nap-plot-tools" %}
{% set version = "0.0.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/nap-plot-tools-{{ version }}.tar.gz
  sha256: db21328868cf5f12fffb5b887034f221e6a7cd8bf3fac71053b82fea90e0512d

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - python >=3.8
    - setuptools
  run:
    - cmap
    - numpy
    - python >=3.8
    - qtpy
    - deprecated

test:
  imports:
    - nap_plot_tools
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - pyqt

about:
  home: https://pypi.org/project/nap-plot-tools
  summary: A NAPari PLOTter TOOLbar and tools for additional functionalities.
  license: BSD-3-Clause
  license_file: LICENSE
  dev_url: https://github.com/zoccoler/nap-plot-tools

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - zoccoler
